### ISSUE TITLE
Device Polling

### ISSUE THREAD

**Issue by BufferOverflowed** [valkjsaaa/node-switchmate3#2]
Im using this node-switchmate3 library as im able to communicate with the first gen Switchmate devices. I can discover and toggle using this library, however Im unable to get device polling to work. The output I get after entering the command followed by my device ID, is:

Finding xxxxxx
found 
connected
disconnected 

without showing the device state. Were you able to get this polling working on the 3rd gen switches using this library?

**Comment by jlippold** [comment]
Did anyone figure this out? A toggle command instead of just On/Off would be great

**Comment by valkjsaaa** [comment]
@RIPv1  I just implemented probe.switchmate3 for getting the status of the switch

**Comment by valkjsaaa** [comment]
@jlippold Unfortunately, as far as I know, the new Switchmate firmware no longer support toggling. If you like, you can implement toggling by first read the status and then send command to flip the status.

**Comment by jlippold** [comment]
If you got status working, I can code a toggle myself. Thanks @valkjsaaa
