### ISSUE TITLE
Permission Denied when trying to open node-switchmate3 as root after installing as root

### ISSUE THREAD

**Issue by jeffl78** [valkjsaaa/node-switchmate3#3]
I installed node-switchmate3 as root and I get permission denied when trying to run the command /usr/lib/node-modules/node-switchmate3/bin/discover.switchmate3 like this:

root@raspberrypi:~# /usr/lib/node_modules/node-switchmate3/bin/discover.switchmate3
bash: /usr/lib/node_modules/node-switchmate3/bin/discover.switchmate3: Permission denied

I have tried a number of different chmod commands and have tried installing it using global --unsafe perm, and adding the "--allow root"  suffex during the install.  Nothing seems to help, any assistance would be appreciated.  

Thanks for your time.

**Comment by basesnow** [comment]
I was able to get this to work when I used chmod u+x *

**Comment by jlippold** [comment]
you don't need to do install as root, or chmod

just prefix it with node

```
node /usr/lib/node_modules/node-switchmate3/bin/discover.switchmate3
```
